### ISSUE TITLE
Keeps trailing newline on one-line pastes

### ISSUE THREAD

**Issue by ryansb** [psss/edd#6]
When I copy multiple lines of text then edit down to one line, edd doesn't remove the trailing newline. This is a pain if that one line is only a part of some terminal input.

Would you accept a patch that strips trailing newlines, or even all trailing whitespace?

**Comment by psss** [comment]
Indeed, the extra new line at the end of the text should not be
appended unless present in the original text. Would preserving the
original state (include if original contained and omit if omitted)
resolve your use case?

**Comment by ryansb** [comment]
I don't think it would, since I often have some group of lines (e.g. output from some listing command or dashboard) that I need to compact into the arguments to some other command. Because it's pasted from a multiline source, a newline is often included at the end that I don't want/need in the output. 

Perhaps a solution would be `--strip` and `--no-strip` options to the `edd` command, with the default being the existing behavior. I'd be happy to put up a patch for review if you'd rather see concrete implementation.

**Comment by psss** [comment]
I see. Thanks for clarification. Using a dedicated option could be
a solution. I was also thinking about providing some simple config
file `.edd` which could contain something like `EDD_STRIP=true`.

However, for now the thing is so fresh, I think we can experiment
a little bit more. Perhaps always removing the final EOL would not
break anything. Let's try it this simple way as the first step :-)

Would you please prepare a patch for this? I think we could remove
the whole trailing white space. Thanks.

**Comment by psss** [comment]
This has been resolved by 389defc. Thanks Ryan.
